#!/bin/bash

make

for i in {1..10}; do
    ./make_pattern "/home/dom/ThirdYear/Summer/Test Data/english.50MB" $1 > pattern
    ./parameterised_test >> parameterised_test_m_$1
    ./exact_test >> exact_test_m_$1
    ./kmp_test >> kmp_test_m_$1
done

rm pattern
make clean
