#!/bin/bash

make gen-pattern
make kmp-test

for i in {1..10}; do
    ./make_pattern "/home/dom/ThirdYear/Summer/Test Data/english.50MB" $1 > pattern
    ./kmp_test "/home/dom/ThirdYear/Summer/Test Data/english.50MB" pattern >> kmp_test_m_$1
done

rm pattern
make gen-pattern-clean
make kmp-test-clean
