#!/bin/bash

make

for i in {1..10}; do
    ./make_pattern "/home/dom/ThirdYear/Summer/Test Data/english.50MB" $1 > pattern
    ./parameterised_test "/home/dom/ThirdYear/Summer/Test Data/english.50MB" pattern
    ./exact_test "/home/dom/ThirdYear/Summer/Test Data/english.50MB" pattern
done


rm pattern
make clean
